In [1]:
import torch

# initializing

In [2]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]])
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device="cuda")
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [5]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device="cuda",
                         requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [7]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device=device,
                         requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [8]:
print(my_tensor.dtype)

torch.float32


In [9]:
print(my_tensor.device)

cuda:0


In [10]:
print(my_tensor.shape)

torch.Size([2, 3])


In [11]:
x = torch.empty(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [0., 0., 0.]], device='cuda:0', requires_grad=True)


In [12]:
x = torch.zeros(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0', requires_grad=True)


In [13]:
x = torch.rand(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[0.6606, 0.9766, 0.7534],
        [0.3755, 0.0244, 0.9237],
        [0.0651, 0.3501, 0.9101]], device='cuda:0', requires_grad=True)


In [14]:
x = torch.ones(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', requires_grad=True)


In [15]:
x = torch.eye(5,5, device=device, requires_grad=True)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], device='cuda:0', requires_grad=True)


In [16]:
x = torch.arange(start=0,end=10, step=2, device=device)
print(x)

tensor([0, 2, 4, 6, 8], device='cuda:0')


In [17]:
x = torch.linspace(start=0.1, end=1, steps=10, device=device)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000], device='cuda:0')


In [18]:
x = torch.empty(size=(1, 5), device=device).normal_(mean=0, std=1)
print(x)

tensor([[ 0.2624,  1.3417,  0.5701,  1.5768, -1.2506]], device='cuda:0')


In [19]:
x = torch.empty(size=(1, 5), device=device).uniform_(0, 1)
print(x)

tensor([[0.6428, 0.5159, 0.3025, 0.1297, 0.3212]], device='cuda:0')


In [20]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## convert types

In [21]:
tensor = torch.arange(4, device=device)
print(tensor)

tensor([0, 1, 2, 3], device='cuda:0')


In [22]:
print(tensor.bool())

tensor([False,  True,  True,  True], device='cuda:0')


In [23]:
print(tensor.short())

tensor([0, 1, 2, 3], device='cuda:0', dtype=torch.int16)


In [24]:
print(tensor.long())
print(tensor.long().dtype)

tensor([0, 1, 2, 3], device='cuda:0')
torch.int64


In [25]:
print(tensor.half())

tensor([0., 1., 2., 3.], device='cuda:0', dtype=torch.float16)


In [26]:
print(tensor.float())
print(tensor.float().dtype)

tensor([0., 1., 2., 3.], device='cuda:0')
torch.float32


In [27]:
print(tensor.double())

tensor([0., 1., 2., 3.], device='cuda:0', dtype=torch.float64)


In [28]:
import numpy as np

In [29]:
np_array = np.zeros((5, 5))
print(np_array)
tensor = torch.from_numpy(np_array).cuda()
print(tensor)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)


In [30]:
np_array_back = tensor.cpu().numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Tensor Math

In [31]:
x = torch.tensor([1, 2, 3], device=device)
y = torch.tensor([9, 8, 7], device=device)

In [32]:
z = torch.empty(3, device=device)
print(z)

tensor([2.3694e-38, 2.3694e-38, 2.3694e-38], device='cuda:0')


In [33]:
torch.add(x, y, out=z)
print(z)

tensor([10., 10., 10.], device='cuda:0')


In [34]:
z = torch.add(x, y)
print(z)

tensor([10, 10, 10], device='cuda:0')


In [35]:
z = x + y
print(z)

tensor([10, 10, 10], device='cuda:0')


In [36]:
torch.subtract(x, y, out=z)
print(z)

tensor([-8, -6, -4], device='cuda:0')


In [37]:
z = torch.subtract(x, y)
print(z)

tensor([-8, -6, -4], device='cuda:0')


In [38]:
z = x - y
print(z)

tensor([-8, -6, -4], device='cuda:0')


In [39]:
z = torch.true_divide(x, y)
print(z)

tensor([0.1111, 0.2500, 0.4286], device='cuda:0')


In [40]:
z = torch.true_divide(x, 2)
print(z)

tensor([0.5000, 1.0000, 1.5000], device='cuda:0')


In [41]:
# inplace
t = torch.zeros(3, device=device)
print(t)
t.add_(x)
print(t)

tensor([0., 0., 0.], device='cuda:0')
tensor([1., 2., 3.], device='cuda:0')


In [42]:
t = torch.zeros(3, device=device)
print(t)
t += x
print(t)

tensor([0., 0., 0.], device='cuda:0')
tensor([1., 2., 3.], device='cuda:0')


In [43]:
z = x.pow(2)
print(z)

tensor([1, 4, 9], device='cuda:0')


In [44]:
z = x ** 2
print(z)

tensor([1, 4, 9], device='cuda:0')


In [45]:
z = x > 0
print(z)

tensor([True, True, True], device='cuda:0')


In [46]:
z = x < 0
print(z)

tensor([False, False, False], device='cuda:0')


In [47]:
x1 = torch.rand(size=(2, 5), device=device)
x2 = torch.rand(size=(5, 3), device=device)

In [48]:
x3 = torch.mm(x1, x2)
print(x3)

tensor([[1.4605, 1.1563, 1.2490],
        [1.7167, 1.4920, 1.3881]], device='cuda:0')


In [49]:
x3 = x1.mm(x2)
print(x3)

tensor([[1.4605, 1.1563, 1.2490],
        [1.7167, 1.4920, 1.3881]], device='cuda:0')


In [50]:
matrix_exp = torch.rand(size=(5, 5), device=device)
x = matrix_exp.matrix_power(3)
print(x)

tensor([[1.8956, 3.6844, 2.9428, 3.4917, 3.0106],
        [2.9475, 5.8960, 4.6783, 5.6190, 4.7472],
        [3.3984, 6.6487, 5.2690, 6.3013, 5.3537],
        [2.9680, 5.7429, 4.5734, 5.4260, 4.6518],
        [2.0619, 4.1180, 3.2853, 3.9245, 3.3409]], device='cuda:0')


In [51]:
x = torch.tensor([1, 2, 3], device=device, dtype=torch.float32)
y = torch.tensor([9, 8, 7], device=device, dtype=torch.float32)
z = x * y
print(z)

tensor([ 9., 16., 21.], device='cuda:0')


In [52]:
z = x @ y
print(z)

tensor(46., device='cuda:0')


In [53]:
batch = 32
n = 10
m = 20
p = 30

In [54]:
tensor1 = torch.rand(size=(batch, n, m))
tensor2 = torch.rand(size=(batch, m, p))

In [55]:
out_bmm = torch.bmm(tensor1, tensor2)
print(out_bmm)

tensor([[[4.6921, 4.7139, 5.9440,  ..., 5.1540, 5.3884, 4.6632],
         [5.2749, 4.9764, 5.0974,  ..., 5.8602, 4.9896, 4.7105],
         [4.4598, 3.6652, 5.3172,  ..., 5.5857, 4.6923, 4.0505],
         ...,
         [4.5735, 3.6323, 4.1373,  ..., 3.5163, 4.6811, 3.9947],
         [3.5413, 3.7478, 4.3632,  ..., 4.2603, 4.5535, 4.7084],
         [4.5070, 4.2959, 5.0581,  ..., 5.3175, 5.1965, 4.2793]],

        [[5.5718, 4.7122, 3.8230,  ..., 5.2944, 4.9062, 4.4028],
         [7.4324, 5.6986, 4.8842,  ..., 5.0563, 6.7229, 6.3127],
         [5.5758, 4.1105, 4.0878,  ..., 3.6491, 5.1939, 4.4830],
         ...,
         [6.4386, 4.9854, 5.0872,  ..., 4.8446, 6.9300, 5.2621],
         [6.1198, 4.5241, 4.7225,  ..., 4.8551, 5.8246, 5.9899],
         [5.5886, 4.4486, 5.1727,  ..., 4.5064, 5.9254, 4.7717]],

        [[5.2479, 3.1215, 5.3576,  ..., 3.8315, 4.6441, 5.2102],
         [4.3048, 3.0261, 5.0714,  ..., 3.4908, 4.5398, 5.2515],
         [4.7897, 2.7793, 5.1873,  ..., 3.6156, 4.6369, 5.

## Broadcasting

In [56]:
x1 = torch.rand(size=(5, 5))
x2 = torch.rand(size=(1, 5))
print(x1)
print(x2)

tensor([[0.5193, 0.6521, 0.5383, 0.6302, 0.4239],
        [0.4713, 0.9010, 0.8007, 0.2071, 0.7842],
        [0.4140, 0.5725, 0.4511, 0.9131, 0.7874],
        [0.6454, 0.5112, 0.9257, 0.2349, 0.5441],
        [0.4038, 0.0105, 0.4845, 0.6871, 0.4058]])
tensor([[0.4777, 0.7164, 0.9486, 0.0486, 0.4922]])


In [57]:
z = x1 - x2
print(z)

tensor([[ 0.0416, -0.0643, -0.4102,  0.5816, -0.0683],
        [-0.0064,  0.1846, -0.1479,  0.1586,  0.2920],
        [-0.0637, -0.1439, -0.4974,  0.8645,  0.2952],
        [ 0.1677, -0.2052, -0.0229,  0.1863,  0.0519],
        [-0.0739, -0.7058, -0.4641,  0.6385, -0.0864]])


In [58]:
z = x1 ** x2
print(z)

tensor([[0.7312, 0.7362, 0.5558, 0.9778, 0.6555],
        [0.6981, 0.9280, 0.8099, 0.9264, 0.8872],
        [0.6562, 0.6706, 0.4700, 0.9956, 0.8890],
        [0.8113, 0.6184, 0.9294, 0.9321, 0.7411],
        [0.6485, 0.0384, 0.5029, 0.9819, 0.6415]])


## other useful operations

In [59]:
sum_x = torch.sum(x, dim=0)
print(sum_x)

tensor(6., device='cuda:0')


In [60]:
print(x)
values, indices = torch.max(x, dim=0)
print(values, indices)

tensor([1., 2., 3.], device='cuda:0')
tensor(3., device='cuda:0') tensor(2, device='cuda:0')


In [61]:
values, indices = torch.min(x, dim=0)
print(values, indices)

tensor(1., device='cuda:0') tensor(0, device='cuda:0')


In [62]:
abs_x = torch.abs(x)
print(abs_x)

tensor([1., 2., 3.], device='cuda:0')


In [63]:
z = torch.argmax(x, dim=0) # only index
print(z)

tensor(2, device='cuda:0')


In [64]:
z = torch.argmin(x, dim=0) # only index
print(z)

tensor(0, device='cuda:0')


In [65]:
mean_x = torch.mean(x.float(), dim=0)
print(mean_x)

tensor(2., device='cuda:0')


In [66]:
z = torch.eq(x, y)
print(z)

tensor([False, False, False], device='cuda:0')


In [67]:
sorted_y, indices = torch.sort(y, dim=0, descending=False)
print(sorted_y, indices)

tensor([7., 8., 9.], device='cuda:0') tensor([2, 1, 0], device='cuda:0')


In [68]:
x4 = torch.rand(size=(1, 10), device=device) * 10
print(x4)

tensor([[8.3085, 1.6077, 2.5288, 4.2500, 7.4923, 6.9717, 6.7579, 3.2992, 0.4786,
         9.8067]], device='cuda:0')


In [69]:
z = torch.clamp(x4, min=4, max=8)
print(z)

tensor([[8.0000, 4.0000, 4.0000, 4.2500, 7.4923, 6.9717, 6.7579, 4.0000, 4.0000,
         8.0000]], device='cuda:0')


In [70]:
x = torch.tensor([1, 0, 1, 1, 1], device=device, dtype=torch.bool)
z = torch.any(x)
print(z)

tensor(True, device='cuda:0')


In [71]:
z = torch.all(x)
print(z)

tensor(False, device='cuda:0')


# Tensor Indexing

In [72]:
batch_size = 10
features = 25
x = torch.rand(size=(batch_size, features), device=device)

In [73]:
x[0, :]

tensor([0.2046, 0.7710, 0.9180, 0.1779, 0.3840, 0.3773, 0.4043, 0.4724, 0.5085,
        0.3315, 0.2738, 0.4675, 0.0176, 0.3994, 0.5544, 0.1129, 0.7681, 0.6538,
        0.2336, 0.3271, 0.5677, 0.4471, 0.6301, 0.7359, 0.7168],
       device='cuda:0')

In [74]:
x[0]

tensor([0.2046, 0.7710, 0.9180, 0.1779, 0.3840, 0.3773, 0.4043, 0.4724, 0.5085,
        0.3315, 0.2738, 0.4675, 0.0176, 0.3994, 0.5544, 0.1129, 0.7681, 0.6538,
        0.2336, 0.3271, 0.5677, 0.4471, 0.6301, 0.7359, 0.7168],
       device='cuda:0')

In [75]:
x[0].shape

torch.Size([25])

In [76]:
x[:, 0]

tensor([0.2046, 0.2094, 0.1883, 0.8672, 0.8146, 0.2251, 0.4933, 0.8700, 0.9102,
        0.7951], device='cuda:0')

In [77]:
x[:, 0].shape

torch.Size([10])

In [78]:
x[2, 0:10]

tensor([0.1883, 0.9523, 0.7421, 0.4037, 0.7094, 0.3560, 0.7555, 0.0843, 0.9475,
        0.2518], device='cuda:0')

In [79]:
x[2, 0:10] = torch.tensor([0.6742, 0.7751, 0.2046, 0.2539,
                           0.0352, 5.5212, 5.9559, 5.5626, 5.0052, 5.5009], device=device)

In [80]:
x[2, 0:10]

tensor([0.6742, 0.7751, 0.2046, 0.2539, 0.0352, 5.5212, 5.9559, 5.5626, 5.0052,
        5.5009], device='cuda:0')

In [81]:
x[2]

tensor([0.6742, 0.7751, 0.2046, 0.2539, 0.0352, 5.5212, 5.9559, 5.5626, 5.0052,
        5.5009, 0.8526, 0.2454, 0.1487, 0.8739, 0.2743, 0.7691, 0.2984, 0.7313,
        0.0204, 0.8899, 0.0812, 0.7680, 0.8674, 0.0801, 0.0667],
       device='cuda:0')

In [83]:
x = torch.rand(10, device=device)
print(x)
indices = [2, 5, 8]
print(x[indices])

tensor([0.0250, 0.0461, 0.9681, 0.9759, 0.7713, 0.1682, 0.2049, 0.4175, 0.0899,
        0.7860], device='cuda:0')
tensor([0.9681, 0.1682, 0.0899], device='cuda:0')


In [86]:
x = torch.rand(size=(3, 5), device=device)

In [87]:
print(x)

tensor([[0.1724, 0.9068, 0.6190, 0.3594, 0.7001],
        [0.6337, 0.0864, 0.7460, 0.0760, 0.8460],
        [0.0235, 0.1691, 0.0821, 0.7116, 0.5856]], device='cuda:0')


In [88]:
rows = torch.tensor([1, 0], device=device)
cols = torch.tensor([4, 0], device=device)

In [89]:
print(x[rows, cols])

tensor([0.8460, 0.1724], device='cuda:0')


In [94]:
x = torch.arange(10, device=device)
print(
    x[(x < 2) | (x > 8)]
)

tensor([0, 1, 9], device='cuda:0')


In [95]:
x = torch.arange(10, device=device)
print(
    x[(x > 5) & (x < 8)]
)

tensor([6, 7], device='cuda:0')


In [96]:
print(x[x.remainder(2) == 0])

tensor([0, 2, 4, 6, 8], device='cuda:0')


In [97]:
torch.where(x > 5, x, x**2)

tensor([ 0,  1,  4,  9, 16, 25,  6,  7,  8,  9], device='cuda:0')

In [98]:
torch.tensor([0,0,1,2,2,3,4], device=device).unique()

tensor([0, 1, 2, 3, 4], device='cuda:0')

In [99]:
x.ndimension()

1

In [100]:
tensor = torch.rand(size=(5, 6, 7), device=device)
print(tensor)

tensor([[[0.6604, 0.8371, 0.1231, 0.8883, 0.1286, 0.4204, 0.0095],
         [0.8829, 0.0220, 0.6473, 0.0327, 0.8373, 0.5762, 0.3572],
         [0.2817, 0.0036, 0.2431, 0.6430, 0.6438, 0.8991, 0.2367],
         [0.9771, 0.6541, 0.2011, 0.7130, 0.8563, 0.6179, 0.4115],
         [0.1296, 0.1506, 0.8903, 0.7375, 0.5069, 0.3776, 0.2162],
         [0.2983, 0.4125, 0.6065, 0.4859, 0.8018, 0.4269, 0.7840]],

        [[0.6987, 0.0543, 0.1557, 0.7935, 0.0099, 0.1673, 0.8113],
         [0.1431, 0.4464, 0.6668, 0.2574, 0.7201, 0.2013, 0.3360],
         [0.5593, 0.5039, 0.1739, 0.6880, 0.3079, 0.3480, 0.1226],
         [0.7417, 0.7103, 0.4743, 0.6663, 0.1866, 0.5714, 0.4449],
         [0.8182, 0.2105, 0.3306, 0.4120, 0.8403, 0.6596, 0.3278],
         [0.9635, 0.6898, 0.1466, 0.6316, 0.5994, 0.0219, 0.1755]],

        [[0.1229, 0.1158, 0.3821, 0.7284, 0.7511, 0.7006, 0.6479],
         [0.8643, 0.7229, 0.9192, 0.5390, 0.1075, 0.4352, 0.3703],
         [0.8460, 0.8451, 0.3034, 0.4464, 0.5498, 0.7775, 

In [101]:
tensor.ndimension()

3

In [102]:
tensor.numel()

210

# Reshaping