In [2]:
import torch

In [3]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]])
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [5]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device="cuda")
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [6]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device="cuda",
                         requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [8]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device=device,
                         requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
