In [1]:
import torch

# initializing

In [2]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]])
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device="cuda")
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [5]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device="cuda",
                         requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [7]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device=device,
                         requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [8]:
print(my_tensor.dtype)

torch.float32


In [9]:
print(my_tensor.device)

cuda:0


In [10]:
print(my_tensor.shape)

torch.Size([2, 3])


In [11]:
x = torch.empty(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [0., 0., 0.]], device='cuda:0', requires_grad=True)


In [12]:
x = torch.zeros(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0', requires_grad=True)


In [13]:
x = torch.rand(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[0.0902, 0.9770, 0.3136],
        [0.5306, 0.5507, 0.2791],
        [0.8907, 0.5883, 0.3912]], device='cuda:0', requires_grad=True)


In [14]:
x = torch.ones(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', requires_grad=True)


In [15]:
x = torch.eye(5,5, device=device, requires_grad=True)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], device='cuda:0', requires_grad=True)


In [16]:
x = torch.arange(start=0,end=10, step=2, device=device)
print(x)

tensor([0, 2, 4, 6, 8], device='cuda:0')


In [17]:
x = torch.linspace(start=0.1, end=1, steps=10, device=device)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000], device='cuda:0')


In [18]:
x = torch.empty(size=(1, 5), device=device).normal_(mean=0, std=1)
print(x)

tensor([[ 1.9932, -0.2411,  0.5996, -1.0728, -0.5235]], device='cuda:0')


In [19]:
x = torch.empty(size=(1, 5), device=device).uniform_(0, 1)
print(x)

tensor([[0.0621, 0.5367, 0.6660, 0.3781, 0.8659]], device='cuda:0')


In [20]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## convert types

In [21]:
tensor = torch.arange(4, device=device)
print(tensor)

tensor([0, 1, 2, 3], device='cuda:0')


In [22]:
print(tensor.bool())

tensor([False,  True,  True,  True], device='cuda:0')


In [23]:
print(tensor.short())

tensor([0, 1, 2, 3], device='cuda:0', dtype=torch.int16)


In [24]:
print(tensor.long())
print(tensor.long().dtype)

tensor([0, 1, 2, 3], device='cuda:0')
torch.int64


In [25]:
print(tensor.half())

tensor([0., 1., 2., 3.], device='cuda:0', dtype=torch.float16)


In [26]:
print(tensor.float())
print(tensor.float().dtype)

tensor([0., 1., 2., 3.], device='cuda:0')
torch.float32


In [27]:
print(tensor.double())

tensor([0., 1., 2., 3.], device='cuda:0', dtype=torch.float64)


In [28]:
import numpy as np

In [29]:
np_array = np.zeros((5, 5))
print(np_array)
tensor = torch.from_numpy(np_array).cuda()
print(tensor)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)


In [30]:
np_array_back = tensor.cpu().numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Tensor Math

In [31]:
x = torch.tensor([1, 2, 3], device=device)
y = torch.tensor([9, 8, 7], device=device)

In [32]:
z = torch.empty(3, device=device)
print(z)

tensor([2.3694e-38, 2.3694e-38, 2.3694e-38], device='cuda:0')


In [33]:
torch.add(x, y, out=z)
print(z)

tensor([10., 10., 10.], device='cuda:0')


In [34]:
z = torch.add(x, y)
print(z)

tensor([10, 10, 10], device='cuda:0')


In [35]:
z = x + y
print(z)

tensor([10, 10, 10], device='cuda:0')


In [36]:
torch.subtract(x, y, out=z)
print(z)

tensor([-8, -6, -4], device='cuda:0')


In [37]:
z = torch.subtract(x, y)
print(z)

tensor([-8, -6, -4], device='cuda:0')


In [38]:
z = x - y
print(z)

tensor([-8, -6, -4], device='cuda:0')


In [39]:
z = torch.true_divide(x, y)
print(z)

tensor([0.1111, 0.2500, 0.4286], device='cuda:0')


In [40]:
z = torch.true_divide(x, 2)
print(z)

tensor([0.5000, 1.0000, 1.5000], device='cuda:0')


In [41]:
# inplace
t = torch.zeros(3, device=device)
print(t)
t.add_(x)
print(t)

tensor([0., 0., 0.], device='cuda:0')
tensor([1., 2., 3.], device='cuda:0')


In [42]:
t = torch.zeros(3, device=device)
print(t)
t += x
print(t)

tensor([0., 0., 0.], device='cuda:0')
tensor([1., 2., 3.], device='cuda:0')


In [43]:
z = x.pow(2)
print(z)

tensor([1, 4, 9], device='cuda:0')


In [44]:
z = x ** 2
print(z)

tensor([1, 4, 9], device='cuda:0')


In [45]:
z = x > 0
print(z)

tensor([True, True, True], device='cuda:0')


In [46]:
z = x < 0
print(z)

tensor([False, False, False], device='cuda:0')


In [47]:
x1 = torch.rand(size=(2, 5), device=device)
x2 = torch.rand(size=(5, 3), device=device)

In [48]:
x3 = torch.mm(x1, x2)
print(x3)

tensor([[1.2333, 1.1532, 1.3521],
        [0.5862, 0.4987, 0.5002]], device='cuda:0')


In [49]:
x3 = x1.mm(x2)
print(x3)

tensor([[1.2333, 1.1532, 1.3521],
        [0.5862, 0.4987, 0.5002]], device='cuda:0')


In [50]:
matrix_exp = torch.rand(size=(5, 5), device=device)
x = matrix_exp.matrix_power(3)
print(x)

tensor([[5.5268, 3.8308, 2.7220, 3.8104, 3.2955],
        [6.7555, 4.4330, 3.3432, 4.8952, 4.0049],
        [4.4293, 3.1062, 2.2331, 3.0648, 2.6531],
        [5.5603, 3.6275, 2.7294, 3.9241, 3.4386],
        [4.8687, 3.5028, 2.4216, 3.3409, 2.9409]], device='cuda:0')


In [51]:
x = torch.tensor([1, 2, 3], device=device, dtype=torch.float32)
y = torch.tensor([9, 8, 7], device=device, dtype=torch.float32)
z = x * y
print(z)

tensor([ 9., 16., 21.], device='cuda:0')


In [52]:
z = x @ y
print(z)

tensor(46., device='cuda:0')


In [53]:
batch = 32
n = 10
m = 20
p = 30

In [54]:
tensor1 = torch.rand(size=(batch, n, m))
tensor2 = torch.rand(size=(batch, m, p))

In [55]:
out_bmm = torch.bmm(tensor1, tensor2)
print(out_bmm)

tensor([[[4.6926, 4.9837, 6.1079,  ..., 5.5569, 4.5007, 6.6437],
         [4.3535, 4.1289, 5.4972,  ..., 6.1804, 4.8721, 6.7106],
         [4.7731, 4.9255, 5.7578,  ..., 5.4165, 4.7056, 6.6948],
         ...,
         [3.6387, 4.0204, 4.7974,  ..., 5.4748, 4.0389, 5.8989],
         [5.3132, 5.5008, 6.0789,  ..., 5.8913, 5.2130, 6.1282],
         [4.3941, 4.7718, 5.5689,  ..., 5.0683, 4.4226, 6.0674]],

        [[5.4308, 5.4887, 4.3408,  ..., 7.0416, 5.8303, 5.9679],
         [4.5264, 5.0667, 3.6887,  ..., 5.7921, 5.0460, 5.5146],
         [4.4067, 4.5191, 4.2437,  ..., 6.8599, 5.8725, 5.9063],
         ...,
         [4.6525, 5.8864, 4.0993,  ..., 6.2018, 6.0102, 5.2895],
         [4.9968, 6.3942, 5.3116,  ..., 7.1883, 7.1120, 7.0384],
         [4.4094, 5.0152, 3.2426,  ..., 6.1360, 4.6519, 5.0566]],

        [[3.9374, 5.1950, 3.8161,  ..., 5.6121, 5.6239, 5.3875],
         [5.0095, 5.3994, 4.3805,  ..., 6.6360, 6.9770, 6.0382],
         [4.1307, 5.3609, 3.7263,  ..., 6.0517, 5.2476, 4.

## Broadcasting

In [56]:
x1 = torch.rand(size=(5, 5))
x2 = torch.rand(size=(1, 5))
print(x1)
print(x2)

tensor([[0.1099, 0.9644, 0.0833, 0.0393, 0.8105],
        [0.3281, 0.2717, 0.3382, 0.4114, 0.8820],
        [0.4014, 0.1939, 0.8824, 0.9411, 0.0394],
        [0.0133, 0.4952, 0.8694, 0.0322, 0.8667],
        [0.9612, 0.1754, 0.7339, 0.3562, 0.9807]])
tensor([[0.2066, 0.9949, 0.8055, 0.3434, 0.5015]])


In [57]:
z = x1 - x2
print(z)

tensor([[-0.0967, -0.0305, -0.7222, -0.3041,  0.3090],
        [ 0.1216, -0.7232, -0.4673,  0.0680,  0.3805],
        [ 0.1949, -0.8011,  0.0769,  0.5977, -0.4622],
        [-0.1933, -0.4997,  0.0639, -0.3112,  0.3652],
        [ 0.7546, -0.8195, -0.0716,  0.0127,  0.4792]])


In [58]:
z = x1 ** x2
print(z)

tensor([[0.6337, 0.9646, 0.1351, 0.3290, 0.9000],
        [0.7944, 0.2735, 0.4176, 0.7371, 0.9390],
        [0.8282, 0.1955, 0.9042, 0.9794, 0.1974],
        [0.4097, 0.4970, 0.8934, 0.3072, 0.9308],
        [0.9919, 0.1770, 0.7794, 0.7015, 0.9903]])


## other useful operations

In [59]:
sum_x = torch.sum(x, dim=0)
print(sum_x)

tensor(6., device='cuda:0')


In [60]:
print(x)
values, indices = torch.max(x, dim=0)
print(values, indices)

tensor([1., 2., 3.], device='cuda:0')
tensor(3., device='cuda:0') tensor(2, device='cuda:0')


In [61]:
values, indices = torch.min(x, dim=0)
print(values, indices)

tensor(1., device='cuda:0') tensor(0, device='cuda:0')


In [62]:
abs_x = torch.abs(x)
print(abs_x)

tensor([1., 2., 3.], device='cuda:0')


In [63]:
z = torch.argmax(x, dim=0) # only index
print(z)

tensor(2, device='cuda:0')


In [64]:
z = torch.argmin(x, dim=0) # only index
print(z)

tensor(0, device='cuda:0')


In [65]:
mean_x = torch.mean(x.float(), dim=0)
print(mean_x)

tensor(2., device='cuda:0')


In [66]:
z = torch.eq(x, y)
print(z)

tensor([False, False, False], device='cuda:0')


In [67]:
sorted_y, indices = torch.sort(y, dim=0, descending=False)
print(sorted_y, indices)

tensor([7., 8., 9.], device='cuda:0') tensor([2, 1, 0], device='cuda:0')


In [68]:
x4 = torch.rand(size=(1, 10), device=device) * 10
print(x4)

tensor([[7.1008, 4.6344, 9.1650, 8.8992, 5.3678, 4.2829, 9.5980, 9.7067, 0.4269,
         6.7322]], device='cuda:0')


In [69]:
z = torch.clamp(x4, min=4, max=8)
print(z)

tensor([[7.1008, 4.6344, 8.0000, 8.0000, 5.3678, 4.2829, 8.0000, 8.0000, 4.0000,
         6.7322]], device='cuda:0')


In [70]:
x = torch.tensor([1, 0, 1, 1, 1], device=device, dtype=torch.bool)
z = torch.any(x)
print(z)

tensor(True, device='cuda:0')


In [71]:
z = torch.all(x)
print(z)

tensor(False, device='cuda:0')


# Tensor Indexing

In [72]:
batch_size = 10
features = 25
x = torch.rand(size=(batch_size, features), device=device)

In [73]:
x[0, :]

tensor([0.1055, 0.5579, 0.0668, 0.9130, 0.2015, 0.0723, 0.9472, 0.8567, 0.3535,
        0.8565, 0.6996, 0.4820, 0.2502, 0.0012, 0.6902, 0.6170, 0.3020, 0.6669,
        0.2810, 0.7626, 0.1965, 0.6319, 0.3303, 0.4351, 0.8435],
       device='cuda:0')

In [74]:
x[0]

tensor([0.1055, 0.5579, 0.0668, 0.9130, 0.2015, 0.0723, 0.9472, 0.8567, 0.3535,
        0.8565, 0.6996, 0.4820, 0.2502, 0.0012, 0.6902, 0.6170, 0.3020, 0.6669,
        0.2810, 0.7626, 0.1965, 0.6319, 0.3303, 0.4351, 0.8435],
       device='cuda:0')

In [75]:
x[0].shape

torch.Size([25])

In [76]:
x[:, 0]

tensor([0.1055, 0.1219, 0.2197, 0.8321, 0.6868, 0.6832, 0.5437, 0.3270, 0.7101,
        0.9242], device='cuda:0')

In [77]:
x[:, 0].shape

torch.Size([10])

In [78]:
x[2, 0:10]

tensor([0.2197, 0.0465, 0.9406, 0.9997, 0.4305, 0.4967, 0.3756, 0.1056, 0.4019,
        0.8899], device='cuda:0')

In [79]:
x[2, 0:10] = torch.tensor([0.6742, 0.7751, 0.2046, 0.2539,
                           0.0352, 5.5212, 5.9559, 5.5626, 5.0052, 5.5009], device=device)

In [80]:
x[2, 0:10]

tensor([0.6742, 0.7751, 0.2046, 0.2539, 0.0352, 5.5212, 5.9559, 5.5626, 5.0052,
        5.5009], device='cuda:0')

In [81]:
x[2]

tensor([0.6742, 0.7751, 0.2046, 0.2539, 0.0352, 5.5212, 5.9559, 5.5626, 5.0052,
        5.5009, 0.1460, 0.7699, 0.9482, 0.0771, 0.8425, 0.2533, 0.5629, 0.7892,
        0.0289, 0.1976, 0.4435, 0.5675, 0.1504, 0.5963, 0.6663],
       device='cuda:0')

In [82]:
x = torch.rand(10, device=device)
print(x)
indices = [2, 5, 8]
print(x[indices])

tensor([0.3824, 0.2258, 0.7030, 0.8386, 0.9820, 0.7285, 0.0185, 0.7843, 0.6413,
        0.5380], device='cuda:0')
tensor([0.7030, 0.7285, 0.6413], device='cuda:0')


In [83]:
x = torch.rand(size=(3, 5), device=device)

In [84]:
print(x)

tensor([[0.8149, 0.7088, 0.6727, 0.7263, 0.6518],
        [0.9149, 0.6674, 0.9151, 0.2189, 0.5741],
        [0.1643, 0.8126, 0.0217, 0.2229, 0.2742]], device='cuda:0')


In [85]:
rows = torch.tensor([1, 0], device=device)
cols = torch.tensor([4, 0], device=device)

In [86]:
print(x[rows, cols])

tensor([0.5741, 0.8149], device='cuda:0')


In [87]:
x = torch.arange(10, device=device)
print(
    x[(x < 2) | (x > 8)]
)

tensor([0, 1, 9], device='cuda:0')


In [88]:
x = torch.arange(10, device=device)
print(
    x[(x > 5) & (x < 8)]
)

tensor([6, 7], device='cuda:0')


In [89]:
print(x[x.remainder(2) == 0])

tensor([0, 2, 4, 6, 8], device='cuda:0')


In [90]:
torch.where(x > 5, x, x**2)

tensor([ 0,  1,  4,  9, 16, 25,  6,  7,  8,  9], device='cuda:0')

In [91]:
torch.tensor([0,0,1,2,2,3,4], device=device).unique()

tensor([0, 1, 2, 3, 4], device='cuda:0')

In [92]:
x.ndimension()

1

In [93]:
tensor = torch.rand(size=(5, 6, 7), device=device)
print(tensor)

tensor([[[0.8314, 0.9310, 0.3190, 0.5391, 0.1265, 0.0887, 0.4649],
         [0.3263, 0.0449, 0.8491, 0.1472, 0.7922, 0.3156, 0.8369],
         [0.7205, 0.8444, 0.7695, 0.2843, 0.5820, 0.4017, 0.1744],
         [0.8846, 0.3614, 0.2221, 0.2622, 0.7940, 0.8110, 0.7219],
         [0.7528, 0.4371, 0.0184, 0.8395, 0.7360, 0.0440, 0.3778],
         [0.9679, 0.2465, 0.2663, 0.4379, 0.8331, 0.9284, 0.1348]],

        [[0.5793, 0.8376, 0.8989, 0.6878, 0.6017, 0.0165, 0.5655],
         [0.5373, 0.2182, 0.9088, 0.7851, 0.3534, 0.3056, 0.6951],
         [0.5994, 0.3461, 0.9626, 0.0443, 0.2302, 0.8701, 0.9825],
         [0.4280, 0.6237, 0.7151, 0.3946, 0.0221, 0.6626, 0.8885],
         [0.8254, 0.8477, 0.3380, 0.3901, 0.8026, 0.8888, 0.8005],
         [0.0629, 0.6294, 0.7236, 0.9260, 0.1595, 0.3848, 0.1800]],

        [[0.2144, 0.0810, 0.5658, 0.0028, 0.9667, 0.6852, 0.0448],
         [0.1050, 0.7362, 0.6971, 0.7679, 0.4509, 0.3128, 0.8514],
         [0.9844, 0.3782, 0.5984, 0.3502, 0.9010, 0.5668, 

In [94]:
tensor.ndimension()

3

In [95]:
tensor.numel()

210

# Reshaping

In [96]:
x = torch.arange(9, device=device)

In [97]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8], device='cuda:0')


In [98]:
x_3x3 = x.view(3,3)

In [99]:
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], device='cuda:0')


In [100]:
x_3x3 = x.reshape(3, 3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]], device='cuda:0')


In [103]:
y = x_3x3.t()
print(y)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]], device='cuda:0')


In [104]:
y.view(9)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [106]:
y.contiguous().view(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8], device='cuda:0')

In [107]:
x1 = torch.rand(size=(2, 5))
x2 = torch.rand(size=(2, 5))
print(x1, x2, sep="\n")

tensor([[0.9682, 0.2431, 0.3516, 0.6544, 0.3063],
        [0.5069, 0.0460, 0.2374, 0.4862, 0.3415]])
tensor([[0.4269, 0.3679, 0.5842, 0.7243, 0.4437],
        [0.0901, 0.1341, 0.2053, 0.2046, 0.0544]])


In [108]:
torch.cat((x1, x2), dim=0)

tensor([[0.9682, 0.2431, 0.3516, 0.6544, 0.3063],
        [0.5069, 0.0460, 0.2374, 0.4862, 0.3415],
        [0.4269, 0.3679, 0.5842, 0.7243, 0.4437],
        [0.0901, 0.1341, 0.2053, 0.2046, 0.0544]])

In [111]:
torch.cat((x1, x2), dim=1)

tensor([[0.9682, 0.2431, 0.3516, 0.6544, 0.3063, 0.4269, 0.3679, 0.5842, 0.7243,
         0.4437],
        [0.5069, 0.0460, 0.2374, 0.4862, 0.3415, 0.0901, 0.1341, 0.2053, 0.2046,
         0.0544]])

In [112]:
z = x1.view(-1)
print(z)

tensor([0.9682, 0.2431, 0.3516, 0.6544, 0.3063, 0.5069, 0.0460, 0.2374, 0.4862,
        0.3415])


In [113]:
batch = 64
x = torch.rand((batch, 2, 5))
print(x.shape)
z = x.view(batch, -1)
print(z.shape)

torch.Size([64, 2, 5])
torch.Size([64, 10])


In [114]:
z = x.permute(0, 2, 1)
print(z.shape)

torch.Size([64, 5, 2])


In [115]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [119]:
x.unsqueeze(1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [120]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x)

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])


In [121]:
z = x.squeeze(1)
print(z)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])


[video ref](https://www.youtube.com/watch?v=x9JiIFvlUwk)