In [2]:
import torch

# initializing

In [3]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]])
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [5]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device="cuda")
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [6]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device="cuda",
                         requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [8]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device=device,
                         requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [9]:
print(my_tensor.dtype)

torch.float32


In [10]:
print(my_tensor.device)

cuda:0


In [11]:
print(my_tensor.shape)

torch.Size([2, 3])


In [12]:
x = torch.empty(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [0., 0., 0.]], device='cuda:0', requires_grad=True)


In [13]:
x = torch.zeros(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0', requires_grad=True)


In [14]:
x = torch.rand(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[0.3071, 0.1684, 0.4886],
        [0.3232, 0.3456, 0.4381],
        [0.1397, 0.0721, 0.1789]], device='cuda:0', requires_grad=True)


In [15]:
x = torch.ones(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', requires_grad=True)


In [16]:
x = torch.eye(5,5, device=device, requires_grad=True)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], device='cuda:0', requires_grad=True)


In [17]:
x = torch.arange(start=0,end=10, step=2, device=device)
print(x)

tensor([0, 2, 4, 6, 8], device='cuda:0')


In [18]:
x = torch.linspace(start=0.1, end=1, steps=10, device=device)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000], device='cuda:0')


In [19]:
x = torch.empty(size=(1, 5), device=device).normal_(mean=0, std=1)
print(x)

tensor([[-0.4520, -0.1646,  0.5093, -0.9653,  0.9076]], device='cuda:0')


In [20]:
x = torch.empty(size=(1, 5), device=device).uniform_(0, 1)
print(x)

tensor([[0.3520, 0.9735, 0.5215, 0.5763, 0.0378]], device='cuda:0')


In [21]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## convert types

In [22]:
tensor = torch.arange(4, device=device)
print(tensor)

tensor([0, 1, 2, 3], device='cuda:0')


In [23]:
print(tensor.bool())

tensor([False,  True,  True,  True], device='cuda:0')


In [24]:
print(tensor.short())

tensor([0, 1, 2, 3], device='cuda:0', dtype=torch.int16)


In [25]:
print(tensor.long())
print(tensor.long().dtype)

tensor([0, 1, 2, 3], device='cuda:0')
torch.int64


In [26]:
print(tensor.half())

tensor([0., 1., 2., 3.], device='cuda:0', dtype=torch.float16)


In [27]:
print(tensor.float())
print(tensor.float().dtype)

tensor([0., 1., 2., 3.], device='cuda:0')
torch.float32


In [28]:
print(tensor.double())

tensor([0., 1., 2., 3.], device='cuda:0', dtype=torch.float64)


In [29]:
import numpy as np

In [30]:
np_array = np.zeros((5, 5))
print(np_array)
tensor = torch.from_numpy(np_array).cuda()
print(tensor)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)


In [31]:
np_array_back = tensor.cpu().numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Tensor Math

In [32]:
x = torch.tensor([1, 2, 3], device=device)
y = torch.tensor([9, 8, 7], device=device)

In [33]:
z = torch.empty(3, device=device)
print(z)

tensor([2.3694e-38, 2.3694e-38, 2.3694e-38], device='cuda:0')


In [34]:
torch.add(x, y, out=z)
print(z)

tensor([10., 10., 10.], device='cuda:0')


In [35]:
z = torch.add(x, y)
print(z)

tensor([10, 10, 10], device='cuda:0')


In [36]:
z = x + y
print(z)

tensor([10, 10, 10], device='cuda:0')


In [37]:
torch.subtract(x, y, out=z)
print(z)

tensor([-8, -6, -4], device='cuda:0')


In [38]:
z = torch.subtract(x, y)
print(z)

tensor([-8, -6, -4], device='cuda:0')


In [39]:
z = x - y
print(z)

tensor([-8, -6, -4], device='cuda:0')


In [40]:
z = torch.true_divide(x, y)
print(z)

tensor([0.1111, 0.2500, 0.4286], device='cuda:0')


In [41]:
z = torch.true_divide(x, 2)
print(z)

tensor([0.5000, 1.0000, 1.5000], device='cuda:0')


In [42]:
# inplace
t = torch.zeros(3, device=device)
print(t)
t.add_(x)
print(t)

tensor([0., 0., 0.], device='cuda:0')
tensor([1., 2., 3.], device='cuda:0')


In [43]:
t = torch.zeros(3, device=device)
print(t)
t += x
print(t)

tensor([0., 0., 0.], device='cuda:0')
tensor([1., 2., 3.], device='cuda:0')


In [45]:
z = x.pow(2)
print(z)

tensor([1, 4, 9], device='cuda:0')


In [46]:
z = x ** 2
print(z)

tensor([1, 4, 9], device='cuda:0')


In [47]:
z = x > 0
print(z)

tensor([True, True, True], device='cuda:0')


In [48]:
z = x < 0
print(z)

tensor([False, False, False], device='cuda:0')


In [49]:
x1 = torch.rand(size=(2, 5), device=device)
x2 = torch.rand(size=(5, 3), device=device)

In [50]:
x3 = torch.mm(x1, x2)
print(x3)

tensor([[0.3362, 0.2864, 0.4890],
        [1.6308, 1.2064, 2.0296]], device='cuda:0')


In [51]:
x3 = x1.mm(x2)
print(x3)

tensor([[0.3362, 0.2864, 0.4890],
        [1.6308, 1.2064, 2.0296]], device='cuda:0')


In [52]:
matrix_exp = torch.rand(size=(5, 5), device=device)
x = matrix_exp.matrix_power(3)
print(x)

tensor([[4.8368, 4.1041, 3.2424, 3.8233, 4.5231],
        [3.7010, 3.0667, 2.4930, 3.1416, 3.5432],
        [5.8153, 4.9269, 3.9919, 4.8834, 5.6421],
        [3.6667, 3.1248, 2.4605, 3.0466, 3.4484],
        [6.1510, 5.2576, 4.1652, 4.9407, 5.8186]], device='cuda:0')


In [62]:
x = torch.tensor([1, 2, 3], device=device, dtype=torch.float32)
y = torch.tensor([9, 8, 7], device=device, dtype=torch.float32)
z = x * y
print(z)

tensor([ 9., 16., 21.], device='cuda:0')


In [63]:
z = x @ y
print(z)

tensor(46., device='cuda:0')


In [64]:
batch = 32
n = 10
m = 20
p = 30

In [65]:
tensor1 = torch.rand(size=(batch, n, m))
tensor2 = torch.rand(size=(batch, m, p))

In [66]:
out_bmm = torch.bmm(tensor1, tensor2)
print(out_bmm)

tensor([[[4.6520, 5.0643, 4.2458,  ..., 4.5995, 5.9139, 4.9606],
         [5.3245, 6.2050, 6.4586,  ..., 5.7924, 6.1406, 5.6234],
         [4.2691, 5.5730, 5.7451,  ..., 5.3302, 5.4612, 5.1205],
         ...,
         [3.0538, 2.9257, 4.3012,  ..., 3.7741, 3.3757, 3.3655],
         [3.7232, 4.5268, 4.5941,  ..., 4.4686, 4.2839, 3.9542],
         [3.5210, 4.0559, 4.1594,  ..., 3.4924, 4.4531, 3.2551]],

        [[5.0955, 5.1594, 6.8434,  ..., 6.9885, 4.3784, 6.0611],
         [4.0566, 3.2749, 4.7499,  ..., 5.3484, 3.7203, 5.0497],
         [4.0452, 3.9655, 5.6362,  ..., 5.3266, 3.9713, 5.1606],
         ...,
         [5.7498, 3.6534, 6.2087,  ..., 6.2540, 4.3877, 6.6210],
         [4.6947, 3.8080, 5.4706,  ..., 5.5545, 3.5170, 5.0927],
         [4.7376, 3.4496, 5.6856,  ..., 4.7625, 4.0880, 4.9344]],

        [[5.4288, 5.8458, 6.0402,  ..., 5.8326, 7.0178, 5.5526],
         [5.0256, 4.3703, 3.3050,  ..., 4.4235, 5.3782, 3.7828],
         [4.7162, 5.1760, 5.3521,  ..., 4.9315, 5.6070, 5.

## Broadcasting

In [68]:
x1 = torch.rand(size=(5, 5))
x2 = torch.rand(size=(1, 5))
print(x1)
print(x2)

tensor([[0.1266, 0.6464, 0.9318, 0.2478, 0.5631],
        [0.4546, 0.8720, 0.2295, 0.1507, 0.1896],
        [0.7152, 0.7269, 0.8802, 0.0723, 0.4145],
        [0.7839, 0.8664, 0.9785, 0.9597, 0.3136],
        [0.4380, 0.4503, 0.7072, 0.2411, 0.1051]])
tensor([[0.3939, 0.3247, 0.4097, 0.0688, 0.2344]])


In [69]:
z = x1 - x2
print(z)

tensor([[-0.2673,  0.3217,  0.5221,  0.1790,  0.3287],
        [ 0.0607,  0.5473, -0.1802,  0.0819, -0.0448],
        [ 0.3213,  0.4023,  0.4705,  0.0035,  0.1801],
        [ 0.3900,  0.5417,  0.5688,  0.8909,  0.0792],
        [ 0.0440,  0.1256,  0.2976,  0.1723, -0.1293]])


In [70]:
z = x1 ** x2
print(z)

tensor([[0.4430, 0.8679, 0.9715, 0.9085, 0.8741],
        [0.7331, 0.9565, 0.5472, 0.8779, 0.6772],
        [0.8763, 0.9016, 0.9490, 0.8346, 0.8135],
        [0.9085, 0.9545, 0.9911, 0.9972, 0.7620],
        [0.7224, 0.7718, 0.8677, 0.9068, 0.5897]])


## other useful operations

In [74]:
sum_x = torch.sum(x, dim=0)
print(sum_x)

tensor(6., device='cuda:0')


In [77]:
print(x)
values, indices = torch.max(x, dim=0)
print(values, indices)

tensor([1., 2., 3.], device='cuda:0')
tensor(3., device='cuda:0') tensor(2, device='cuda:0')


In [76]:
values, indices = torch.min(x, dim=0)
print(values, indices)

tensor(1., device='cuda:0') tensor(0, device='cuda:0')


In [78]:
abs_x = torch.abs(x)
print(abs_x)

tensor([1., 2., 3.], device='cuda:0')


In [79]:
z = torch.argmax(x, dim=0) # only index
print(z)

tensor(2, device='cuda:0')


In [81]:
z = torch.argmin(x, dim=0) # only index
print(z)

tensor(0, device='cuda:0')


In [83]:
mean_x = torch.mean(x.float(), dim=0)
print(mean_x)

tensor(2., device='cuda:0')


In [84]:
z = torch.eq(x, y)
print(z)

tensor([False, False, False], device='cuda:0')


In [85]:
sorted_y, indices = torch.sort(y, dim=0, descending=False)
print(sorted_y, indices)

tensor([7., 8., 9.], device='cuda:0') tensor([2, 1, 0], device='cuda:0')


In [87]:
x4 = torch.rand(size=(1, 10), device=device) * 10
print(x4)

tensor([[7.5622, 5.2950, 9.7554, 8.2688, 4.0839, 2.3666, 5.8982, 8.1205, 3.6056,
         3.4313]], device='cuda:0')


In [88]:
z = torch.clamp(x4, min=4, max=8)
print(z)

tensor([[7.5622, 5.2950, 8.0000, 8.0000, 4.0839, 4.0000, 5.8982, 8.0000, 4.0000,
         4.0000]], device='cuda:0')


In [89]:
x = torch.tensor([1, 0, 1, 1, 1], device=device, dtype=torch.bool)
z = torch.any(x)
print(z)

tensor(True, device='cuda:0')


In [90]:
z = torch.all(x)
print(z)

tensor(False, device='cuda:0')
