In [2]:
import torch

# initializing

In [3]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]])
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [5]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device="cuda")
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [6]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device="cuda",
                         requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [8]:
my_tensor = torch.tensor([[1,2,3], [4, 5, 6]], dtype=torch.float32, device=device,
                         requires_grad=True)
print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)


In [9]:
print(my_tensor.dtype)

torch.float32


In [10]:
print(my_tensor.device)

cuda:0


In [11]:
print(my_tensor.shape)

torch.Size([2, 3])


In [14]:
x = torch.empty(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [0., 0., 0.]], device='cuda:0', requires_grad=True)


In [15]:
x = torch.zeros(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0', requires_grad=True)


In [17]:
x = torch.rand(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[0.7830, 0.1188, 0.4405],
        [0.7340, 0.5382, 0.4521],
        [0.9593, 0.2700, 0.4731]], device='cuda:0', requires_grad=True)


In [18]:
x = torch.ones(size=(3,3), device=device, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0', requires_grad=True)


In [20]:
x = torch.eye(5,5, device=device, requires_grad=True)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], device='cuda:0', requires_grad=True)


In [22]:
x = torch.arange(start=0,end=10, step=2, device=device)
print(x)

tensor([0, 2, 4, 6, 8], device='cuda:0')


In [24]:
x = torch.linspace(start=0.1, end=1, steps=10, device=device)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000], device='cuda:0')


In [25]:
x = torch.empty(size=(1, 5), device=device).normal_(mean=0, std=1)
print(x)

tensor([[ 0.7674, -1.1810,  1.1603, -0.3321, -0.8445]], device='cuda:0')


In [26]:
x = torch.empty(size=(1, 5), device=device).uniform_(0, 1)
print(x)

tensor([[0.7821, 0.5683, 0.4620, 0.6171, 0.0104]], device='cuda:0')


In [27]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# convert types

In [29]:
tensor = torch.arange(4, device=device)
print(tensor)

tensor([0, 1, 2, 3], device='cuda:0')


In [30]:
print(tensor.bool())

tensor([False,  True,  True,  True], device='cuda:0')


In [31]:
print(tensor.short())

tensor([0, 1, 2, 3], device='cuda:0', dtype=torch.int16)


In [33]:
print(tensor.long())
print(tensor.long().dtype)

tensor([0, 1, 2, 3], device='cuda:0')
torch.int64


In [34]:
print(tensor.half())

tensor([0., 1., 2., 3.], device='cuda:0', dtype=torch.float16)


In [36]:
print(tensor.float())
print(tensor.float().dtype)

tensor([0., 1., 2., 3.], device='cuda:0')
torch.float32


In [37]:
print(tensor.double())

tensor([0., 1., 2., 3.], device='cuda:0', dtype=torch.float64)


In [38]:
import numpy as np

In [49]:
np_array = np.zeros((5, 5))
print(np_array)
tensor = torch.from_numpy(np_array).cuda()
print(tensor)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)


In [58]:
np_array_back = tensor.cpu().numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
