In [2]:
import tensorflow as tf

# Initialization of tensors

In [3]:
# scaler
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
x = tf.constant(4, shape=(2, 2), dtype=tf.float32)
print(x)

tf.Tensor(
[[4. 4.]
 [4. 4.]], shape=(2, 2), dtype=float32)


In [7]:
x = tf.constant([[1,2,3], [4, 5, 6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [9]:
x = tf.ones(shape=(3, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [10]:
x = tf.zeros(shape=(3, 2))
print(x)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [12]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [14]:
x = tf.random.normal(shape=(3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[-1.3547946  -0.91588885  0.44302168]
 [ 1.0322783  -0.2580786  -0.3541972 ]
 [ 0.03148658  1.8860928  -0.67296547]], shape=(3, 3), dtype=float32)


In [15]:
x = tf.random.uniform(shape=(1, 3), maxval=1, minval=0)
print(x)

tf.Tensor([[0.49473512 0.6929532  0.88097465]], shape=(1, 3), dtype=float32)


In [16]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [17]:
x = tf.range(start=1, limit=10, delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [19]:
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


## mathematical Operations

In [20]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

In [21]:
z = tf.add(x, y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [22]:
z = x + y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [23]:
z = tf.subtract(x, y)
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [24]:
z = x - y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [25]:
z = tf.divide(x, y)
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [26]:
z = x / y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [27]:
z = tf.multiply(x, y)
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [29]:
z = x * y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [33]:
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [37]:
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [38]:
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [39]:
x = tf.random.normal(shape=(2, 3))
y = tf.random.normal(shape=(3, 4))

In [40]:
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[ 0.88117206 -1.8543469   0.5768615  -2.6852217 ]
 [-0.51733404 -4.743336    1.0185701  -3.2115848 ]], shape=(2, 4), dtype=float32)


In [41]:
z = x @ y
print(z)

tf.Tensor(
[[ 0.88117206 -1.8543469   0.5768615  -2.6852217 ]
 [-0.51733404 -4.743336    1.0185701  -3.2115848 ]], shape=(2, 4), dtype=float32)
